# This configuration file should contain all required configuration parameters
# for the phylogenetic workflow to run to completion.
#
# Define optional config parameters with their default values here so that users
# do not have to dig through the workflows to figure out the default values
filter:
  min_length: 3000
  exclude_where: 
    Africa: "host!='Camel' region!='Africa'"
    Asia: "host!='Camel' region!='Asia'"
  

traits:
  columns: "host country"
